apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-mlops-api
  template:
    metadata:
      labels:
        app: mini-mlops-api
    spec:
      containers:
        - name: api
          image: mini-mlops-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
